{
 "title": "FlexLM Simulator",
 "tags": [
  "flexlm",
  "simulator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flexlm_server_status", "legendFormat": "{{app}} {{fqdn}}:{{port}}" }
   ]
  },
  {
   "title": "Feature Issued vs Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "flexlm_feature_issued", "legendFormat": "issued {{name}}" },
    { "expr": "flexlm_feature_used", "legendFormat": "used {{name}}" }
   ]
  },
  {
   "title": "Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "flexlm_feature_reserved_groups", "legendFormat": "group {{group}} {{name}}" },
    { "expr": "flexlm_feature_reserved_host", "legendFormat": "host {{host}} {{name}}" }
   ]
  },
  {
   "title": "User Usage By Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "flexlm_feature_used_users", "legendFormat": "{{name}} {{user}} {{version}}" }
   ]
  },
  {
   "title": "Feature Expiration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flexlm_feature_expiration_seconds",
     "legendFormat": "{{name}} {{version}}"
    }
   ]
  }
 ]
}